#!/usr/bin/env bash
test -z $(type -p) || { echo bash required; exit 1; }
set -e
set -u
source ${RRCONFINC}

echo '#' $require
echo RRCONF=$RRCONF
echo RRCONF_REPOS=$RRCONF_REPOS
echo RRDEBUG=$RRDEBUG
echo RRLOGLEVEL=$RRLOGLEVEL
echo RRMODPULL=$RRMODPULL

echo '# Clone order according to ' $RRCONF_REPOS
for repo in $(run-parts --list $RRCONF_REPOS); do
  echo $(<$repo)MODULE.git
done
